### ISSUE TITLE
Meta issue

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/camera-trap-vueapp#240]
計畫建立：
- [x] 填寫計畫時間時用日曆選定後，會往前跳一天
- [ ] 資料公開日期，若日期超過計畫起始時間的５年後，文字雖會顯示紅色，但無相關錯誤訊息，摸索許久才找出無法新增計畫的原因（建議增加錯誤提示，日期預設為計畫起始日期的５年後）
- [ ] 新增計畫點選取消後頁面空白
- [ ] 編輯設定中，子樣區應為獨立欄位

資料上傳：
- [ ] 上傳紀錄的時間不正確
- [ ] 上傳後顯示為上傳中，轉換頁面後紀錄消失，看不到上傳狀況，似乎要等到發現錯誤後才會顯示
- [x] 上傳結果錯誤訊息不清楚
- [ ] 上傳 zip 檔一直無法成功
- [ ] 其中一次嘗試一直沒看到上傳紀錄，不知結果為何

資料編輯：
- [ ] 物種名稱不在清單上點選回報管理員，跳出編輯畫面，但回到資料編輯頁面時仍顯示鎖定，但可以進入編輯模式，退出後仍顯示鎖定
- [ ] 物種名稱不在清單上點選回報管理員，跳出編輯畫面後未回報，但再次檢視資料時，該物種名稱已不再有警告標示

資料視覺化：
- [x] 地圖點選顯示林班地似乎沒有反應
- [ ] 缺物種時空間分布

資料篩選與計算：
- [ ] 資料篩選完無法變更篩選的條件，回上頁後原篩選條件也消失，需重新輸入
- [ ] 資料篩選完無法直接用篩選的結果進行計算
- [ ] 資料計算結果呈現的起始時間與原設定不同
- [ ] 資料計算每小時有效照片張數與每小時目擊事件次數計算有問題，3/51 and 2/51 皆顯示為 0。且特生建議應計算每千小時張數和次數
- [ ] 測試到一半，頁面無法選擇物種，以致無法進行計算
- [ ] 測試到一半，頁面顯示資料讀取中就卡住了
- [ ] 缺少平均偵測天數比例、相機間變異的計算
- [ ] 不確定計算結果是否正確，也不確定是否能將不同輸入名稱的同一物種納入篩選和計算

資料輸出：
- [ ] 沒找到輸出成 DwC Archive 的方式

其它：
- [x] 首頁底部點選“立即開始使用”後，即使已經登入，仍會出現要求登入的視窗
- [x] 請提供測試帳號，否則無法看到舊資料
- [ ] 缺少進階標註功能

**Comment by cjk-halodule** [comment]
Invalid.
